spring.application.name=ems
spring.datasource.url=jdbc:h2:mem:test6
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.operationsSorter=method




#spring.datasource.url=jdbc:mySql://localhost:3306/Country_data
#spring.datasource.name=root
#spring.datasource.password=your password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hafeezmohammad4567@gmail.com
spring.mail.password=tekg axwq lxml hpqq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

